language: csharp
os: osx 

# Only run builds on specific branches
branches:
    only:
    - master

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
    on_failure: never


install:
- sudo -E sh ./TravisScripts/install.sh

script:
- sudo -E sh ./TravisScripts/build.sh

# Environmental global variables used in install and build Scripts
env:
    global:
    - UNITYCI_NAME="UnityOptics-CMPS115-2019Su"
